version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    hostname: nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
